apiVersion: apps/v1
kind: Deployment
metadata:
  name: kautrack-api
  labels:
    {{- include "kautrack.labels" . | nindent 4 }}
    app.kubernetes.io/name: kautrack-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kautrack-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kautrack-api
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: Always
          command: ["./bin/docker-entrypoint-api.sh"]
          ports:
            - containerPort: {{ .Values.api.port }}
              name: http
          envFrom:
            - configMapRef:
                name: kautrack-config
            - secretRef:
                name: {{ .Values.secretName }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /api/v1/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
