apiVersion: apps/v1
kind: Deployment
metadata:
  name: kautrack-web
  labels:
    {{- include "kautrack.labels" . | nindent 4 }}
    app.kubernetes.io/name: kautrack-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kautrack-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kautrack-web
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: "{{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.web.port }}
              name: http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
