apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: kautrack/credentials
