apiVersion: v1
kind: Service
metadata:
  name: kautrack-space
  labels:
    {{- include "kautrack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.space.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: kautrack-space
