# Staging overrides — auto-updated by CI
# Tag: staging-d955215 (2026-03-31T03:01:29Z)
images:
  api:
    tag: "staging-d955215"
  web:
    tag: "staging-d955215"
  admin:
    tag: "staging-d955215"
  space:
    tag: "staging-d955215"
  live:
    tag: "staging-d955215"
