# Staging overrides — auto-updated by CI
# Tag: staging-1dfc05c (2026-03-27T15:42:35Z)
images:
  api:
    tag: "staging-1dfc05c"
  web:
    tag: "staging-1dfc05c"
  admin:
    tag: "staging-1dfc05c"
  space:
    tag: "staging-1dfc05c"
  live:
    tag: "staging-1dfc05c"
